version: '3'

services:
  app:
    build: .
    ports:
      - '3001:3000'
    volumes:
      - .:/home/node/app
    container_name: app-bff
    restart: always
  db:
    platform: linux/x86_64
    image: postgres
    container_name: database-bff
    ports:
      - '5434:5432'

    volumes:
      - .postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bffDb

  redis:
    image: redis
    container_name: app-bff-redis
    restart: always
    volumes:
      - redis-data:/data
    ports:
      - '6379:6379'
    environment:
      - REDIS_PASSWORD=redis_password123
    #command: ["redis-server", "--requirepass", "your_redis_password"]

volumes:
  redis-data:
