version: '3'

services:
  app:
    build: .
    ports:
      - '3001:3000'
    volumes:
      - .:/home/node/app
    container_name: app-bff
    restart: always
  db:
    env_file:
      - ./envs/.env
    platform: linux/x86_64
    image: postgres
    container_name: database-bff
    restart: always
    ports:
      - '5434:5432'

    volumes:
      - .postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}

  redis:
    env_file:
      - ./envs/.env
    image: redis
    container_name: app-bff-redis
    restart: always
    volumes:
      - redis-data:/data
    ports:
      - '6379:6379'
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}

volumes:
  redis-data:
